### ISSUE TITLE
密码是否没兼容特殊格式

### ISSUE THREAD

**Issue by qiangzi7723** [Gcaufy/sshman#3]
G大，我刚刚尝试使用了下，但是报错了

```
Automaticlly login to the only one SSH config. run 's new' to add more.
Try to login server【XXX】
/Users/zengzhiqiang/.sshman/sshman: line 209: XXX!@: syntax error in expression (error token is "!@")
```

**Comment by Gcaufy** [comment]
try `s -v`

我尝试把密码修改为 `XXXX!@XXXX` 可以正常登陆，不报错。

我的版本是 `1.0.4`

**Comment by qiangzi7723** [comment]
好，我下次抽时间试试，我的密码格式是这样的123@#xxx，不知道是不是@#之类的特殊符号影响。我有空研究下，或者看看源码，不用麻烦G大了

**Comment by qiangzi7723** [comment]
vaaa!@#111 看了下，应该是#影响的，不是@号。保存下来的密码变成了 vaaa!@ 后面丢失了

**Comment by Gcaufy** [comment]
好的，我周末看看测试一下 #。

**Comment by qiangzi7723** [comment]
嗯，我是特意更新到了1.06测试的，发现确实不行

**Comment by Gcaufy** [comment]
![image](https://user-images.githubusercontent.com/2182004/82750693-5e64f380-9de4-11ea-8380-f9736383b9af.png)

我测试了一下，没有什么问题呀。

你试试直接修改  ~/.sshman/servers.db 这个文件中的密码试试看呢？

**Comment by qiangzi7723** [comment]
可以了，我手动修改了这个文件，重新将密码覆盖就行了。原来的这份文件，#后面的内容丢失了，导致密码错误。感谢~
